services:
  - type: web
    plan: free
    name: Quick-Rename-Bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    repo: https://github.com/TonyStarkBotz/Quick-Rename-Bot.git
    branch: main
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: FORCE_SUB
        sync: false
      - key: LOG_CHANNEL
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_URL
        sync: false
      - key: RKN_PIC
        sync: false
      - key: ADMIN
        sync: false
      - key: STRING_SESSION
        sync: false
